import { userSetup } from "./user/mod.ts";
import { fileSetup } from "./file/mod.ts";
import { tagSetup } from "./tag/mod.ts";
import { organizationSetup } from "./organization/mod.ts";
import { unitSetup } from "./unit/mod.ts";
import { processSetup } from "./process/mod.ts";
import { processStepSetup } from "./processStep/mod.ts";
import { purchasingRequestSetup } from "./purchasingRequest/mod.ts";
import { stateSetup } from "./state/mod.ts";
import { citySetup } from "./city/mod.ts";
import { manufacturerSetup } from "./manufacturer/mod.ts";
import { wareTypeSetup } from "./wareType/mod.ts";
import { wareClassSetup } from "./wareClass/mod.ts";
import { wareGroupSetup } from "./wareGroup/mod.ts";
import { wareModelSetup } from "./wareModel/mod.ts";
import { wareSetup } from "./ware/mod.ts";
import { stuffSetup } from "./stuff/mod.ts";
import { storeSetup } from "./store/mod.ts";
import { stepApprovalSetup } from "./stepApproval/mod.ts";

export const functionsSetup = () => {
	userSetup();
	fileSetup();
	tagSetup();
	organizationSetup();
	unitSetup();
	processSetup();
	processStepSetup();
	purchasingRequestSetup();
	stateSetup();
	citySetup();
	manufacturerSetup();
	wareTypeSetup();
	wareClassSetup();
	wareGroupSetup();
	wareModelSetup();
	wareSetup();
	stuffSetup();
	storeSetup();
	stepApprovalSetup();
};
