import { faIR } from "date-fns-jalali/locale/fa-IR";
import {
  addDays,
  addMonths,
  addWeeks,
  addYears,
  differenceInCalendarDays,
  differenceInCalendarMonths,
  eachMonthOfInterval,
  eachYearOfInterval,
  endOfISOWeek,
  endOfMonth,
  endOfWeek,
  endOfYear,
  format,
  getISOWeek,
  getMonth,
  getWeek,
  getYear,
  isAfter,
  isBefore,
  isDate,
  isSameDay,
  isSameMonth,
  isSameYear,
  max,
  min,
  setMonth,
  setYear,
  startOfDay,
  startOfISOWeek,
  startOfMonth,
  startOfWeek,
  startOfYear,
} from "date-fns-jalali";

export function createJalaliDateLibOverrides() {
  return {
    addDays,
    addMonths,
    addWeeks,
    addYears,
    differenceInCalendarDays,
    differenceInCalendarMonths,
    eachMonthOfInterval,
    eachYearOfInterval,
    endOfISOWeek,
    endOfMonth,
    endOfWeek,
    endOfYear,
    format,
    getISOWeek,
    getMonth,
    getWeek,
    getYear,
    isAfter,
    isBefore,
    isDate,
    isSameDay,
    isSameMonth,
    isSameYear,
    max,
    min,
    setMonth,
    setYear,
    startOfDay,
    startOfISOWeek,
    startOfMonth,
    startOfWeek,
    startOfYear,
  };
}

export const jalaliFaIR = faIR;
