import { addSetup } from "./add/mod.ts";
import { getSetup } from "./get/mod.ts";
import { getsSetup } from "./gets/mod.ts";
import { updateSetup } from "./update/mod.ts";
import { updateRelationsSetup } from "./updateRelations/mod.ts";
import { removeSetup } from "./remove/mod.ts";
import { countSetup } from "./count/mod.ts";
import { submitSetup } from "./submit/mod.ts";
import { warehouseCheckSetup } from "./warehouseCheck/mod.ts";

import { getHistorySetup } from "./getHistory/mod.ts";
import { addStuffSetup } from "./addStuff/mod.ts";
import { checkStoreAvailabilitySetup } from "./checkStoreAvailability/mod.ts";
import { removeFromPurchaseSetup } from "./removeFromPurchase/mod.ts";
import { updateStuffStatusSetup } from "./updateStuffStatus/mod.ts";
import { selectTenderOfferSetup } from "./selectTenderOffer/mod.ts";
import { removeTenderSelectionSetup } from "./removeTenderSelection/mod.ts";
import { getPendingByUnitSetup } from "./getPendingByUnit/mod.ts";
import { finalizeSetup } from "./finalize/mod.ts";

export const purchasingRequestSetup = () => {
  addSetup();
  updateSetup();
  updateRelationsSetup();
  getSetup();
  getsSetup();
  removeSetup();
  countSetup();
  submitSetup();
  warehouseCheckSetup();
  getHistorySetup();
  addStuffSetup();
  checkStoreAvailabilitySetup();
  removeFromPurchaseSetup();
  updateStuffStatusSetup();
  selectTenderOfferSetup();
  removeTenderSelectionSetup();
  getPendingByUnitSetup();
  finalizeSetup();
};
