/**
 * WareType — Top-level product classification.
 *
 * Level 1 of the 4-level warehouse hierarchy: WareType → WareClass → WareGroup → WareModel.
 * Broad categories like "Laboratory Equipment" or "Office Supplies". Has no relations
 * defined here; reverse relations (wareClasses, wareGroups, wareModels, wares, stuffs)
 * are auto-generated by Lesan from child models.
 *
 * Pure fields: name, enName
 * Relations: (none defined — reverse relations auto-generated from child models)
 *
 * @example
 * // Top-level category for lab equipment
 * {
 *   _id: ObjectId("..."),
 *   name: "تجهیزات آزمایشگاهی",
 *   enName: "Laboratory Equipment",
 *   createdAt: ISODate("2024-01-01T00:00:00Z"),
 *   updatedAt: ISODate("2024-01-01T00:00:00Z")
 * }
 */
import { coreApp } from "../mod.ts";
import { optional, string } from "lesan";
import { createUpdateAt } from "@lib";

export const wareType_pure = {
  name: string(),
  enName: optional(string()),
  ...createUpdateAt,
};

export const wareType_relations = {};

export const wareTypes = () =>
  coreApp.odm.newModel("wareType", wareType_pure, wareType_relations, {
    createIndex: {
      indexSpec: {
        name: "text",
        enName: "text",
      },
    },
  });
